version: '3'
services:
  backend:
    image: ghcr.io/pruglo92/performer-of-long-tasks:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATASOURCE_URL=r2dbc:postgresql://localhost:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - DATASOURCE_NAME=postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres